//! Stable, transport-neutral contracts between QSONaut and a HostBridge.
//!
//! Control messages are JSON text frames. Audio is deliberately not JSON: it
//! is sent as binary frames with a [`MediaFrameHeader`] followed by little
//! endian PCM samples. This keeps the hot path compact and leaves room for a
//! future Opus/codec negotiation without changing radio control messages.

use rigwright::Mode;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

pub const PROTOCOL_VERSION: u16 = 2;
pub const MEDIA_HEADER_VERSION: u8 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ClientHello {
    pub protocol_version: u16,
    pub client_name: String,
    pub access_key: String,
    pub password: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct HostHello {
    pub protocol_version: u16,
    pub session_id: Uuid,
    pub host_name: String,
    pub capabilities: Capabilities,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct Capabilities {
    pub radio_control: bool,
    pub radio_devices: Vec<RadioDeviceInfo>,
    pub audio_capture: bool,
    pub audio_playback: bool,
    pub media_codecs: Vec<AudioCodec>,
    /// Physical or logical capture inputs available on the host. The client
    /// selects one by stable ID rather than guessing a device path.
    pub audio_sources: Vec<AudioSourceInfo>,
    /// Host playback outputs available for client-to-host media.
    pub audio_outputs: Vec<AudioOutputInfo>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RadioDeviceInfo {
    /// Stable ID generated by the host adapter, not a raw `/dev` path.
    pub id: String,
    pub label: String,
    pub driver: RadioDriver,
    pub model: Option<String>,
    pub transport: RadioTransportKind,
    pub in_use: bool,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RadioDriver {
    IcomCiv,
    YaesuCat,
    YaesuLegacyCat,
    KenwoodCat,
    Rigctld,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RadioTransportKind {
    UsbSerial,
    Network,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioSourceInfo {
    pub id: String,
    pub label: String,
    pub kind: AudioSourceKind,
    pub formats: Vec<AudioFormat>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioOutputInfo {
    pub id: String,
    pub label: String,
    pub formats: Vec<AudioFormat>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AudioSourceKind {
    RadioInput,
    SystemInput,
    NetworkInput,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioFormat {
    pub codec: AudioCodec,
    pub channels: u8,
    pub sample_rate_hz: u32,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AudioCodec {
    PcmS16Le,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MediaDirection {
    HostToClient,
    ClientToHost,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMessage {
    Hello(ClientHello),
    SelectRadio {
        #[serde(default)]
        request_id: Option<String>,
        device_id: String,
    },
    GetState {
        #[serde(default)]
        request_id: Option<String>,
    },
    SetFrequency {
        #[serde(default)]
        request_id: Option<String>,
        frequency_hz: u64,
    },
    SetMode {
        #[serde(default)]
        request_id: Option<String>,
        mode: WireMode,
    },
    SetPtt {
        #[serde(default)]
        request_id: Option<String>,
        enabled: bool,
    },
    SelectAudio {
        #[serde(default)]
        request_id: Option<String>,
        enabled: bool,
        source_id: String,
        format: AudioFormat,
    },
    SelectAudioOutput {
        #[serde(default)]
        request_id: Option<String>,
        enabled: bool,
        output_id: String,
        format: AudioFormat,
    },
    Ping {
        nonce: u64,
    },
    Pong {
        nonce: u64,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMessage {
    Hello(HostHello),
    Ping {
        nonce: u64,
    },
    State(RadioState),
    Ack {
        request_id: Option<String>,
    },
    Error {
        code: String,
        message: String,
        #[serde(default)]
        request_id: Option<String>,
    },
    Pong {
        nonce: u64,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct RadioState {
    pub frequency_hz: Option<u64>,
    pub mode: Option<WireMode>,
    pub ptt: Option<bool>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "UPPERCASE")]
pub enum WireMode {
    Usb,
    Lsb,
    Cw,
    Data,
    Am,
    Fm,
    Wfm,
    Rtty,
    CwReverse,
    RttyReverse,
}

impl From<Mode> for WireMode {
    fn from(mode: Mode) -> Self {
        match mode {
            Mode::Usb => Self::Usb,
            Mode::Lsb => Self::Lsb,
            Mode::Cw => Self::Cw,
            Mode::Data => Self::Data,
            Mode::Am => Self::Am,
            Mode::Fm => Self::Fm,
            Mode::Wfm => Self::Wfm,
            Mode::Rtty => Self::Rtty,
            Mode::CwReverse => Self::CwReverse,
            Mode::RttyReverse => Self::RttyReverse,
        }
    }
}

impl From<WireMode> for Mode {
    fn from(mode: WireMode) -> Self {
        match mode {
            WireMode::Usb => Self::Usb,
            WireMode::Lsb => Self::Lsb,
            WireMode::Cw => Self::Cw,
            WireMode::Data => Self::Data,
            WireMode::Am => Self::Am,
            WireMode::Fm => Self::Fm,
            WireMode::Wfm => Self::Wfm,
            WireMode::Rtty => Self::Rtty,
            WireMode::CwReverse => Self::CwReverse,
            WireMode::RttyReverse => Self::RttyReverse,
        }
    }
}

/// Binary media payload header. All integer fields are little endian.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MediaFrameHeader {
    pub version: u8,
    pub stream_id: u32,
    pub direction: MediaDirection,
    pub codec: AudioCodec,
    pub sequence: u64,
    pub timestamp_samples: u64,
    pub sample_rate_hz: u32,
    pub channels: u8,
    pub payload_bytes: u32,
}

impl MediaFrameHeader {
    pub const BYTES: usize = 1 + 4 + 1 + 1 + 8 + 8 + 4 + 1 + 4;

    pub fn encode(self, output: &mut Vec<u8>) {
        output.push(self.version);
        output.extend_from_slice(&self.stream_id.to_le_bytes());
        output.push(match self.direction {
            MediaDirection::HostToClient => 0,
            MediaDirection::ClientToHost => 1,
        });
        output.push(match self.codec {
            AudioCodec::PcmS16Le => 0,
        });
        output.extend_from_slice(&self.sequence.to_le_bytes());
        output.extend_from_slice(&self.timestamp_samples.to_le_bytes());
        output.extend_from_slice(&self.sample_rate_hz.to_le_bytes());
        output.push(self.channels);
        output.extend_from_slice(&self.payload_bytes.to_le_bytes());
    }

    pub fn decode(input: &[u8]) -> Option<Self> {
        if input.len() < Self::BYTES {
            return None;
        }
        Some(Self {
            version: input[0],
            stream_id: u32::from_le_bytes(input[1..5].try_into().ok()?),
            direction: match input[5] {
                0 => MediaDirection::HostToClient,
                1 => MediaDirection::ClientToHost,
                _ => return None,
            },
            codec: match input[6] {
                0 => AudioCodec::PcmS16Le,
                _ => return None,
            },
            sequence: u64::from_le_bytes(input[7..15].try_into().ok()?),
            timestamp_samples: u64::from_le_bytes(input[15..23].try_into().ok()?),
            sample_rate_hz: u32::from_le_bytes(input[23..27].try_into().ok()?),
            channels: input[27],
            payload_bytes: u32::from_le_bytes(input[28..32].try_into().ok()?),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mode_wire_round_trip_is_stable() {
        let message = ClientMessage::SetMode {
            request_id: None,
            mode: WireMode::CwReverse,
        };
        let json = serde_json::to_string(&message).unwrap();
        assert_eq!(
            json,
            r#"{"type":"set_mode","request_id":null,"mode":"CWREVERSE"}"#
        );
        assert_eq!(
            serde_json::from_str::<ClientMessage>(&json).unwrap(),
            message
        );
    }

    #[test]
    fn audio_header_round_trips() {
        let header = MediaFrameHeader {
            version: MEDIA_HEADER_VERSION,
            stream_id: 2,
            direction: MediaDirection::HostToClient,
            codec: AudioCodec::PcmS16Le,
            sequence: 7,
            timestamp_samples: 336_000,
            sample_rate_hz: 48_000,
            channels: 1,
            payload_bytes: 1920,
        };
        let mut bytes = Vec::new();
        header.encode(&mut bytes);
        assert_eq!(MediaFrameHeader::decode(&bytes), Some(header));
    }

    #[test]
    fn media_header_rejects_unknown_direction_and_preserves_payload_length() {
        let header = MediaFrameHeader {
            version: MEDIA_HEADER_VERSION,
            stream_id: 1,
            direction: MediaDirection::ClientToHost,
            codec: AudioCodec::PcmS16Le,
            sequence: 1,
            timestamp_samples: 0,
            sample_rate_hz: 48_000,
            channels: 1,
            payload_bytes: 4,
        };
        let mut bytes = Vec::new();
        header.encode(&mut bytes);
        assert_eq!(MediaFrameHeader::decode(&bytes), Some(header));
        bytes[5] = 99;
        assert!(MediaFrameHeader::decode(&bytes).is_none());
    }
}
