//! Stable, transport-neutral contracts between QSONaut and a HostBridge.
//!
//! Control messages are JSON text frames. Audio is deliberately not JSON: it
//! is sent as binary frames with a [`MediaFrameHeader`] followed by little
//! endian PCM samples. This keeps the hot path compact and leaves room for a
//! future Opus/codec negotiation without changing radio control messages.

use rigwright::{ControlId, ControlValue, LinkHealth, MeterId, Mode, TunerStatus};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

pub const PROTOCOL_VERSION: u16 = 6;
pub const MEDIA_HEADER_VERSION: u8 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ClientHello {
    pub protocol_version: u16,
    pub client_name: String,
    pub access_key: String,
    pub password: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct HostHello {
    pub protocol_version: u16,
    pub session_id: Uuid,
    pub host_name: String,
    pub capabilities: Capabilities,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct Capabilities {
    pub radio_control: bool,
    pub radio_devices: Vec<RadioDeviceInfo>,
    pub audio_capture: bool,
    pub audio_playback: bool,
    pub media_codecs: Vec<AudioCodec>,
    /// Physical or logical capture inputs available on the host. The client
    /// selects one by stable ID rather than guessing a device path.
    pub audio_sources: Vec<AudioSourceInfo>,
    /// Host playback outputs available for client-to-host media.
    pub audio_outputs: Vec<AudioOutputInfo>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RadioDeviceInfo {
    /// Stable ID generated by the host adapter, not a raw `/dev` path.
    pub id: String,
    pub label: String,
    pub transport: RadioTransportKind,
    pub in_use: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct RadioCapabilitiesInfo {
    pub can_get_frequency: bool,
    pub can_set_frequency: bool,
    pub can_get_mode: bool,
    pub can_set_mode: bool,
    pub can_get_ptt: bool,
    pub can_set_ptt: bool,
    pub can_get_power: bool,
    pub can_set_power: bool,
    pub can_raw_protocol: bool,
    pub controls: Vec<ControlCapability>,
    pub meters: Vec<WireMeterId>,
    pub tuner: bool,
    #[serde(default)]
    pub scope: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ControlCapability {
    pub id: String,
    pub readable: bool,
    pub writable: bool,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[serde(rename_all = "snake_case")]
pub enum WireMeterId {
    Signal,
    Power,
    Swr,
    Alc,
    Compression,
    Current,
    Voltage,
    Temperature,
}

impl From<MeterId> for WireMeterId {
    fn from(id: MeterId) -> Self {
        match id {
            MeterId::Signal => Self::Signal,
            MeterId::Power => Self::Power,
            MeterId::Swr => Self::Swr,
            MeterId::Alc => Self::Alc,
            MeterId::Compression => Self::Compression,
            MeterId::Current => Self::Current,
            MeterId::Voltage => Self::Voltage,
            MeterId::Temperature => Self::Temperature,
        }
    }
}

impl From<WireMeterId> for MeterId {
    fn from(id: WireMeterId) -> Self {
        match id {
            WireMeterId::Signal => Self::Signal,
            WireMeterId::Power => Self::Power,
            WireMeterId::Swr => Self::Swr,
            WireMeterId::Alc => Self::Alc,
            WireMeterId::Compression => Self::Compression,
            WireMeterId::Current => Self::Current,
            WireMeterId::Voltage => Self::Voltage,
            WireMeterId::Temperature => Self::Temperature,
        }
    }
}

pub fn control_id_key(id: ControlId) -> String {
    format!("{id:?}")
}

pub fn control_id_from_key(key: &str) -> Option<ControlId> {
    ControlId::ALL
        .iter()
        .copied()
        .find(|id| format!("{id:?}").eq_ignore_ascii_case(key))
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum WireControlValue {
    Bool(bool),
    U8(u8),
    I32(i32),
    U64(u64),
    Mode(WireMode),
    Vfo(u8),
    Receiver(u8),
    Text(String),
    Raw(Vec<u8>),
}

impl From<ControlValue> for WireControlValue {
    fn from(value: ControlValue) -> Self {
        match value {
            ControlValue::Bool(value) => Self::Bool(value),
            ControlValue::U8(value) => Self::U8(value),
            ControlValue::I32(value) => Self::I32(value),
            ControlValue::U64(value) => Self::U64(value),
            ControlValue::Mode(value) => Self::Mode(value.into()),
            ControlValue::Vfo(value) => Self::Vfo(value),
            ControlValue::Receiver(value) => Self::Receiver(value),
            ControlValue::Text(value) => Self::Text(value),
            ControlValue::Raw(value) => Self::Raw(value),
        }
    }
}

impl From<WireControlValue> for ControlValue {
    fn from(value: WireControlValue) -> Self {
        match value {
            WireControlValue::Bool(value) => Self::Bool(value),
            WireControlValue::U8(value) => Self::U8(value),
            WireControlValue::I32(value) => Self::I32(value),
            WireControlValue::U64(value) => Self::U64(value),
            WireControlValue::Mode(value) => Self::Mode(value.into()),
            WireControlValue::Vfo(value) => Self::Vfo(value),
            WireControlValue::Receiver(value) => Self::Receiver(value),
            WireControlValue::Text(value) => Self::Text(value),
            WireControlValue::Raw(value) => Self::Raw(value),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct WireTunerStatus {
    pub enabled: bool,
    pub tuning: bool,
}

/// Transport counters projected from the selected Rigwright driver.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct WireLinkHealth {
    pub commands_started: Option<u64>,
    pub responses_matched: Option<u64>,
    pub response_timeouts: Option<u64>,
    pub consecutive_timeouts: Option<u32>,
    pub avg_response_micros: Option<u64>,
    pub frames_dropped: Option<u64>,
}

impl From<LinkHealth> for WireLinkHealth {
    fn from(health: LinkHealth) -> Self {
        Self {
            commands_started: health.commands_started,
            responses_matched: health.responses_matched,
            response_timeouts: health.response_timeouts,
            consecutive_timeouts: health.consecutive_timeouts,
            avg_response_micros: health.avg_response.map(|value| value.as_micros() as u64),
            frames_dropped: health.frames_dropped,
        }
    }
}

impl From<WireLinkHealth> for LinkHealth {
    fn from(health: WireLinkHealth) -> Self {
        Self {
            commands_started: health.commands_started,
            responses_matched: health.responses_matched,
            response_timeouts: health.response_timeouts,
            consecutive_timeouts: health.consecutive_timeouts,
            avg_response: health
                .avg_response_micros
                .map(std::time::Duration::from_micros),
            frames_dropped: health.frames_dropped,
        }
    }
}

/// Client-owned native scope configuration. `None` leaves that setting
/// unchanged so the client can apply only the operator changes it owns.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct ScopeConfiguration {
    pub span_hz: Option<u64>,
    pub fixed_edges_hz: Option<(u64, u64)>,
    pub fixed_edge_number: Option<u8>,
    pub hold: Option<bool>,
    pub reference_level_tenths_db: Option<i16>,
    pub sweep_speed: Option<u8>,
    pub center_mode: Option<bool>,
    pub vbw_wide: Option<bool>,
}

impl From<TunerStatus> for WireTunerStatus {
    fn from(status: TunerStatus) -> Self {
        Self {
            enabled: status.enabled,
            tuning: status.tuning,
        }
    }
}

impl From<WireTunerStatus> for TunerStatus {
    fn from(status: WireTunerStatus) -> Self {
        Self {
            enabled: status.enabled,
            tuning: status.tuning,
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RadioDriver {
    IcomCiv,
    YaesuCat,
    YaesuLegacyCat,
    KenwoodCat,
    ElecraftCat,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RadioTransportKind {
    UsbSerial,
    Network,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioSourceInfo {
    pub id: String,
    pub label: String,
    pub kind: AudioSourceKind,
    pub formats: Vec<AudioFormat>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioOutputInfo {
    pub id: String,
    pub label: String,
    pub formats: Vec<AudioFormat>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AudioSourceKind {
    RadioInput,
    SystemInput,
    NetworkInput,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct AudioFormat {
    pub codec: AudioCodec,
    pub channels: u8,
    pub sample_rate_hz: u32,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum AudioCodec {
    PcmS16Le,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum MediaDirection {
    HostToClient,
    ClientToHost,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMessage {
    Hello(ClientHello),
    SelectRadio {
        #[serde(default)]
        request_id: Option<String>,
        device_id: String,
        driver: RadioDriver,
        #[serde(default)]
        model: Option<String>,
        #[serde(default)]
        baud_rate: Option<u32>,
        #[serde(default)]
        radio_address: Option<u8>,
    },
    ConfigureScope {
        #[serde(default)]
        request_id: Option<String>,
        config: ScopeConfiguration,
    },
    StartScope {
        #[serde(default)]
        request_id: Option<String>,
    },
    StopScope {
        #[serde(default)]
        request_id: Option<String>,
    },
    GetState {
        #[serde(default)]
        request_id: Option<String>,
    },
    GetControl {
        #[serde(default)]
        request_id: Option<String>,
        control_id: String,
    },
    SetControl {
        #[serde(default)]
        request_id: Option<String>,
        control_id: String,
        value: WireControlValue,
    },
    GetMeter {
        #[serde(default)]
        request_id: Option<String>,
        meter_id: WireMeterId,
    },
    StartTuner {
        #[serde(default)]
        request_id: Option<String>,
    },
    GetTunerStatus {
        #[serde(default)]
        request_id: Option<String>,
    },
    GetLinkHealth {
        #[serde(default)]
        request_id: Option<String>,
    },
    RawProtocol {
        #[serde(default)]
        request_id: Option<String>,
        frame: Vec<u8>,
    },
    SetFrequency {
        #[serde(default)]
        request_id: Option<String>,
        frequency_hz: u64,
    },
    SetMode {
        #[serde(default)]
        request_id: Option<String>,
        mode: WireMode,
    },
    SetPtt {
        #[serde(default)]
        request_id: Option<String>,
        enabled: bool,
    },
    SelectAudio {
        #[serde(default)]
        request_id: Option<String>,
        enabled: bool,
        source_id: String,
        format: AudioFormat,
    },
    SelectAudioOutput {
        #[serde(default)]
        request_id: Option<String>,
        enabled: bool,
        output_id: String,
        format: AudioFormat,
    },
    Ping {
        nonce: u64,
    },
    Pong {
        nonce: u64,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMessage {
    Hello(HostHello),
    Ping {
        nonce: u64,
    },
    State(RadioState),
    RadioCapabilities(RadioCapabilitiesInfo),
    ControlValue {
        request_id: Option<String>,
        control_id: String,
        value: Option<WireControlValue>,
    },
    MeterValue {
        request_id: Option<String>,
        meter_id: WireMeterId,
        value: Option<u8>,
    },
    ScopeFrame {
        bins: Vec<u8>,
    },
    TunerStatus {
        request_id: Option<String>,
        status: Option<WireTunerStatus>,
    },
    LinkHealth {
        request_id: Option<String>,
        health: WireLinkHealth,
    },
    RawProtocol {
        request_id: Option<String>,
        response: Vec<u8>,
    },
    Ack {
        request_id: Option<String>,
    },
    Error {
        code: String,
        message: String,
        #[serde(default)]
        request_id: Option<String>,
    },
    Pong {
        nonce: u64,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct RadioState {
    pub frequency_hz: Option<u64>,
    pub mode: Option<WireMode>,
    pub ptt: Option<bool>,
    #[serde(default)]
    pub controls: std::collections::BTreeMap<String, WireControlValue>,
    #[serde(default)]
    pub meters: std::collections::BTreeMap<WireMeterId, u8>,
    #[serde(default)]
    pub tuner: Option<WireTunerStatus>,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "UPPERCASE")]
pub enum WireMode {
    Usb,
    Lsb,
    Cw,
    Data,
    Am,
    Fm,
    Wfm,
    Rtty,
    CwReverse,
    RttyReverse,
}

impl From<Mode> for WireMode {
    fn from(mode: Mode) -> Self {
        match mode {
            Mode::Usb => Self::Usb,
            Mode::Lsb => Self::Lsb,
            Mode::Cw => Self::Cw,
            Mode::Data => Self::Data,
            Mode::Am => Self::Am,
            Mode::Fm => Self::Fm,
            Mode::Wfm => Self::Wfm,
            Mode::Rtty => Self::Rtty,
            Mode::CwReverse => Self::CwReverse,
            Mode::RttyReverse => Self::RttyReverse,
        }
    }
}

impl From<WireMode> for Mode {
    fn from(mode: WireMode) -> Self {
        match mode {
            WireMode::Usb => Self::Usb,
            WireMode::Lsb => Self::Lsb,
            WireMode::Cw => Self::Cw,
            WireMode::Data => Self::Data,
            WireMode::Am => Self::Am,
            WireMode::Fm => Self::Fm,
            WireMode::Wfm => Self::Wfm,
            WireMode::Rtty => Self::Rtty,
            WireMode::CwReverse => Self::CwReverse,
            WireMode::RttyReverse => Self::RttyReverse,
        }
    }
}

/// Binary media payload header. All integer fields are little endian.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MediaFrameHeader {
    pub version: u8,
    pub stream_id: u32,
    pub direction: MediaDirection,
    pub codec: AudioCodec,
    pub sequence: u64,
    pub timestamp_samples: u64,
    pub sample_rate_hz: u32,
    pub channels: u8,
    pub payload_bytes: u32,
}

impl MediaFrameHeader {
    pub const BYTES: usize = 1 + 4 + 1 + 1 + 8 + 8 + 4 + 1 + 4;

    pub fn encode(self, output: &mut Vec<u8>) {
        output.push(self.version);
        output.extend_from_slice(&self.stream_id.to_le_bytes());
        output.push(match self.direction {
            MediaDirection::HostToClient => 0,
            MediaDirection::ClientToHost => 1,
        });
        output.push(match self.codec {
            AudioCodec::PcmS16Le => 0,
        });
        output.extend_from_slice(&self.sequence.to_le_bytes());
        output.extend_from_slice(&self.timestamp_samples.to_le_bytes());
        output.extend_from_slice(&self.sample_rate_hz.to_le_bytes());
        output.push(self.channels);
        output.extend_from_slice(&self.payload_bytes.to_le_bytes());
    }

    pub fn decode(input: &[u8]) -> Option<Self> {
        if input.len() < Self::BYTES {
            return None;
        }
        Some(Self {
            version: input[0],
            stream_id: u32::from_le_bytes(input[1..5].try_into().ok()?),
            direction: match input[5] {
                0 => MediaDirection::HostToClient,
                1 => MediaDirection::ClientToHost,
                _ => return None,
            },
            codec: match input[6] {
                0 => AudioCodec::PcmS16Le,
                _ => return None,
            },
            sequence: u64::from_le_bytes(input[7..15].try_into().ok()?),
            timestamp_samples: u64::from_le_bytes(input[15..23].try_into().ok()?),
            sample_rate_hz: u32::from_le_bytes(input[23..27].try_into().ok()?),
            channels: input[27],
            payload_bytes: u32::from_le_bytes(input[28..32].try_into().ok()?),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mode_wire_round_trip_is_stable() {
        let message = ClientMessage::SetMode {
            request_id: None,
            mode: WireMode::CwReverse,
        };
        let json = serde_json::to_string(&message).unwrap();
        assert_eq!(
            json,
            r#"{"type":"set_mode","request_id":null,"mode":"CWREVERSE"}"#
        );
        assert_eq!(
            serde_json::from_str::<ClientMessage>(&json).unwrap(),
            message
        );
    }

    #[test]
    fn capability_operations_round_trip_with_typed_values() {
        let message = ClientMessage::SetControl {
            request_id: Some("control-1".into()),
            control_id: control_id_key(ControlId::RfPower),
            value: WireControlValue::U8(128),
        };
        let json = serde_json::to_string(&message).unwrap();
        assert_eq!(
            serde_json::from_str::<ClientMessage>(&json).unwrap(),
            message
        );
        assert_eq!(control_id_from_key("rfpower"), Some(ControlId::RfPower));
        assert_eq!(WireMeterId::Signal, MeterId::Signal.into());
    }

    #[test]
    fn scope_lifecycle_round_trip_preserves_optional_configuration() {
        let message = ClientMessage::ConfigureScope {
            request_id: Some("scope-config-1".into()),
            config: ScopeConfiguration {
                span_hz: Some(500_000),
                fixed_edges_hz: Some((14_000_000, 14_200_000)),
                fixed_edge_number: Some(4),
                hold: Some(false),
                reference_level_tenths_db: Some(-55),
                sweep_speed: Some(2),
                center_mode: Some(true),
                vbw_wide: Some(true),
            },
        };
        let json = serde_json::to_string(&message).unwrap();
        assert_eq!(
            serde_json::from_str::<ClientMessage>(&json).unwrap(),
            message
        );
        for message in [
            ClientMessage::StartScope {
                request_id: Some("scope-start-1".into()),
            },
            ClientMessage::StopScope {
                request_id: Some("scope-stop-1".into()),
            },
        ] {
            let json = serde_json::to_string(&message).unwrap();
            assert_eq!(
                serde_json::from_str::<ClientMessage>(&json).unwrap(),
                message
            );
        }
    }

    #[test]
    fn driver_service_requests_round_trip_with_request_ids_and_binary_payloads() {
        let raw = ClientMessage::RawProtocol {
            request_id: Some("raw-1".into()),
            frame: vec![0xFE, 0xFE, 0x94, 0xE0, 0x03, 0xFD],
        };
        let json = serde_json::to_string(&raw).unwrap();
        assert_eq!(serde_json::from_str::<ClientMessage>(&json).unwrap(), raw);

        let health = ServerMessage::LinkHealth {
            request_id: Some("health-1".into()),
            health: WireLinkHealth {
                commands_started: Some(12),
                responses_matched: Some(11),
                response_timeouts: Some(1),
                consecutive_timeouts: Some(1),
                avg_response_micros: Some(2_500),
                frames_dropped: Some(3),
            },
        };
        let json = serde_json::to_string(&health).unwrap();
        assert_eq!(
            serde_json::from_str::<ServerMessage>(&json).unwrap(),
            health
        );
    }

    #[test]
    fn audio_header_round_trips() {
        let header = MediaFrameHeader {
            version: MEDIA_HEADER_VERSION,
            stream_id: 2,
            direction: MediaDirection::HostToClient,
            codec: AudioCodec::PcmS16Le,
            sequence: 7,
            timestamp_samples: 336_000,
            sample_rate_hz: 48_000,
            channels: 1,
            payload_bytes: 1920,
        };
        let mut bytes = Vec::new();
        header.encode(&mut bytes);
        assert_eq!(MediaFrameHeader::decode(&bytes), Some(header));
    }

    #[test]
    fn media_header_rejects_unknown_direction_and_preserves_payload_length() {
        let header = MediaFrameHeader {
            version: MEDIA_HEADER_VERSION,
            stream_id: 1,
            direction: MediaDirection::ClientToHost,
            codec: AudioCodec::PcmS16Le,
            sequence: 1,
            timestamp_samples: 0,
            sample_rate_hz: 48_000,
            channels: 1,
            payload_bytes: 4,
        };
        let mut bytes = Vec::new();
        header.encode(&mut bytes);
        assert_eq!(MediaFrameHeader::decode(&bytes), Some(header));
        bytes[5] = 99;
        assert!(MediaFrameHeader::decode(&bytes).is_none());
    }
}
